DBT_CI_CD_DEMO:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 1
      account: IQMTVVB-VH82524
      # host: XR22052.us-east-2.snowflakecomputing.com
      host: IQMTVVB-VH82524.snowflakecomputing.com
      user: "{{ env_var('SNOWFLAKE_USER')}}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: DBT_ROLE
      database: TECHNOVATION
      warehouse: COMPUTE_WH
      schema: DEV
      client_session_keep_alive: False
      query_tag: github_action_query


