name: Our first dbt PR job

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install requirements
        run: pip install dbt-core dbt-snowflake 

      - name: Install dbt dependencies
        run: dbt deps

      - name: dbt run
        run: dbt run
